name: OABSP Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper/scrape_oabsp_subsecoes_full.py

      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: oabsp-subsecoes-planilhas
          path: |
            oabsp_subsecoes_full.csv
            oabsp_subsecoes_full.xlsx
